##
# Environnement de développement du site adhocmusic.com
##

version: '3'

services:

  # le serveur web nginx, sur les ports 80 et 443
  nginx:
    build: ./docker/nginx
    hostname: www
    container_name: adhoc_nginx
    restart: always
    networks:
     adhoc:
       aliases:
         - adhocmusic.test
         - www.adhocmusic.test
         - static.adhocmusic.test
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/adhocmusic.test:ro
      - ./volumes/nginx/log:/var/log/nginx

  # le serveur php, port 9000
  php:
    build: ./docker/php
    hostname: php
    container_name: adhoc_php
    restart: always
    networks:
      adhoc:
        aliases:
          - php.adhocmusic.test
    volumes:
       - .:/var/www/adhocmusic.test
       - ./volumes/php/log:/var/log/php

  # le serveur de base de données, port 3306
  mariadb:
    build: ./docker/mariadb
    hostname: mariadb
    container_name: adhoc_mariadb
    restart: always
    networks:
      adhoc:
        aliases:
          - mariadb.adhocmusic.test
    volumes:
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d
      - ./volumes/mariadb/log:/var/log/mysql
      - ./volumes/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: adhocmusic
      MYSQL_USER: adhocmusic
      MYSQL_PASSWORD: changeme

  # administration de la base de données
  pma:
    image: phpmyadmin/phpmyadmin
    hostname: pma
    container_name: adhoc_pma
    restart: always
    networks:
      adhoc:
        aliases:
          - pma.adhocmusic.test
    ports:
      - 81:80
    environment:
      PMA_HOST: mariadb.adhocmusic.test

networks:
  adhoc:

