##
# Environnement de développement du site adhocmusic.com
##

version: '3'

services:

  # apache:
  #   build: ./docker/apache
  #   #image:
  #   hostname: www
  #   container_name: adhocmusic_apache
  #   restart: always
  #   networks:
  #    adhocmusic:
  #      aliases:
  #        - adhocmusic.dev
  #        - www.adhocmusic.dev
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - .:/var/www/adhocmusic.com:ro
  #     - ./log/apache:/var/log/apache2

  # static:
  #   build: ./docker/static
  #   #image:
  #   hostname: static
  #   container_name: adhocmusic_static
  #   restart: always
  #   networks:
  #    adhocmusic:
  #      aliases:
  #        - static.adhocmusic.dev
  #   ports:
  #     - 82:80
  #     - 445:443
  #   volumes:
  #     - ./static:/var/www/html:ro
  #     - ./log/static:/var/log/apache2

  php:
    build: ./docker/php
    #image:
    hostname: php
    container_name: adhocmusic_php
    restart: always
    networks:
      adhocmusic:
        aliases:
          - php.adhocmusic.dev
    depends_on:
      - mysql
    volumes:
       - .:/var/www/adhocmusic.com
       - ./log/php:/var/log/php

  mysql:
    build: ./docker/mysql
    #image:
    hostname: mysql
    container_name: adhocmusic_mysql
    restart: always
    networks:
      adhocmusic:
        aliases:
          - mysql.adhocmusic.dev
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: adhocmusic
      MYSQL_USER: adhocmusic
      MYSQL_PASSWORD: changeme

  pma:
    #build: ./docker/pma
    image: phpmyadmin/phpmyadmin
    hostname: pma
    container_name: adhocmusic_pma
    restart: always
    networks:
      adhocmusic:
        aliases:
          - pma.adhocmusic.dev
    ports:
      - 81:80
      - 444:443
    environment:
      PMA_HOST: adhocmusic_mysql
      PMA_USER: adhocmusic
      PMA_PASSWORD: changeme

networks:
  adhocmusic:

