##
# Environnement de développement du site adhocmusic.com
##

version: '3'

services:

  # sert contenu statique et dynamique
  apache2:
    build: ./docker/apache2
    #image: httpd:2.4.29-alpine
    hostname: www
    container_name: adhoc_apache
    restart: always
    networks:
     adhoc:
       aliases:
         - adhocmusic.dev
         - www.adhocmusic.dev
         - static.adhocmusic.dev
    ports:
      - 80:80
    volumes:
      - .:/var/www/adhocmusic.dev:ro
      - ./log/apache:/var/log/apache2

  php:
    build: ./docker/php
    #image: php:7.2.2-fpm
    hostname: php
    container_name: adhoc_php
    restart: always
    networks:
      adhoc:
        aliases:
          - php.adhocmusic.dev
    depends_on:
      - mysql
    volumes:
       - .:/var/www/adhocmusic.dev
       - ./log/php:/var/log/php

  mysql:
    build: ./docker/mysql
    image: mysql:5.7.21
    hostname: mysql
    container_name: adhoc_mysql
    restart: always
    networks:
      adhoc:
        aliases:
          - mysql.adhocmusic.dev
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/mysql.conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: adhocmusic
      MYSQL_USER: adhocmusic
      MYSQL_PASSWORD: changeme

  pma:
    image: phpmyadmin/phpmyadmin
    hostname: pma
    container_name: adhoc_pma
    restart: always
    networks:
      adhoc:
        aliases:
          - pma.adhocmusic.dev
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql.adhocmusic.dev

networks:
  adhoc:

