#!/usr/bin/php
<?php

/**
 * Concaténation + compression des feuilles de styles
 */

// fichiers à traiter
$csss = array(
    'reset',        // Reset CSS v2.0 - Meyer
    'main',
    'menu',
    'breadcrumb',
    'box',
    'featured',
    'assoce',
    'agenda',
    'concours',
    'blog',
    'newsletter',
    'articles',
    'admin',
    'pagination',
    'facebook',
    'debug',
);

$out  = 'adhoc.css';
$outm = 'adhoc.min.css';

echo "--- ADHOC CSS CONCAT AND MINIFIER ---\n";

$cnt  = '';
$cntm = '';

foreach($csss as $css)
{
    $in   = $css . '.css';
    echo "Ajout " . $in . " ";

    $file  = file_get_contents(dirname(__FILE__) . '/' . $in);
    $size1 = strlen($file);
    $min   = minify($file);
    $size2 = strlen($min);
    echo $size1 . " octets -> " . $size2 . " octets\n";
    $cnt  .= $file;
    $cntm .= $min;
}

$size = strlen($cnt);
echo "Ecriture " . $out . " (" . $size . " octets)\n";
file_put_contents(dirname(__FILE__) . '/' . $out, $cnt);

$sizem = strlen($cntm);
echo "Ecriture " . $outm . " (" . $sizem . " octets)\n";
file_put_contents(dirname(__FILE__) . '/' . $outm, $cntm);

echo "--- FIN ---\n";

/**
 * compression simpliste d'une feuille de style
 *
 * @param string
 * @return string
 */
function minify($css)
{
    $css = str_replace('{#STATIC_URL#}', 'http://static.adhocmusic.com', $css);

    $css = preg_replace("#/\*.*?\*/#s", '', $css);
    $css = preg_replace( "#\s\s+#", '', $css);
    $css = str_replace(": " , ":"  , $css);
    $css = str_replace("; " , ";"  , $css);
    $css = str_replace(" {" , "{"  , $css);
    $css = str_replace(" }" , "}"  , $css);
    $css = str_replace(", " ,  "," , $css);
    $css = str_replace("{ " , "{"  , $css);
    $css = str_replace(",\n", ","  , $css);
    $css = str_replace("\n}", "}"  , $css);
    $css = str_replace("} " , "}\n", $css);
    $css = str_replace( ';}', '}'  , $css);
    $css = str_replace("\n" , ''   , $css);

    return trim($css);
}
