INSERT INTO `adhoc_style` (`id_style`, `name`) VALUES
(1, 'Rock'),
(2, 'Reggae'),
(3, 'Techno'),
(4, 'Métal'),
(5, 'World'),
(6, 'Chanson'),
(7, 'Hip Hop'),
(8, 'R\'n\'B'),
(9, 'Jazz'),
(10, 'Funk'),
(11, 'Disco'),
(12, 'Classique'),
(13, 'Pop'),
(14, 'Progressif'),
(15, 'Punk'),
(16, 'Ska'),
(17, 'Trip Hop'),
(18, 'Fusion'),
(19, 'Dub'),
(20, 'Heavy'),
(21, 'Drum \'n Bass'),
(22, 'Celtique'),
(23, 'House'),
(24, 'Electro'),
(25, 'Soul'),
(26, 'Blues'),
(27, 'Festif'),
(28, 'Raï'),
(29, 'Folk'),
(30, 'Latino'),
(31, 'Country');
