INSERT INTO `adhoc_type_musicien` (`id_type_musicien`, `name`) VALUES
(1, 'Non défini'),
(2, 'Batteur'),
(3, 'Guitariste'),
(4, 'Bassiste'),
(5, 'Chanteur'),
(6, 'Choriste'),
(7, 'Saxophoniste'),
(8, 'Flûtiste'),
(9, 'Trompettiste'),
(10, 'Tromboniste'),
(11, 'Percussioniste'),
(12, 'Organiste'),
(13, 'Clavieriste'),
(14, 'Sampliste'),
(15, 'Pianiste'),
(16, 'Manager'),
(17, 'DJ'),
(18, 'VJ'),
(19, 'Ingénieur son'),
(20, 'Ingénieur lumière'),
(21, 'Violoniste'),
(22, 'Violoncelliste'),
(23, 'Contrebassiste');
