
INSERT INTO `geo_world_country` (`id_country`, `name`) VALUES
('AD', 'Andorre'),
('AE', 'Émirats Arabes Unis'),
('AF', 'Afghanistan'),
('AG', 'Antigua-et-Barbuda'),
('AI', 'Anguilla'),
('AL', 'Albanie'),
('AM', 'Arménie'),
('AN', 'Antilles néerlandaises'),
('AO', 'Angola'),
('AQ', 'Antarctique'),
('AR', 'Argentine'),
('AS', 'Samoa américaines'),
('AT', 'Autriche'),
('AU', 'Australie'),
('AW', 'Aruba'),
('AX', 'Åland'),
('AZ', 'Azerbaïdjan'),
('BA', 'Bosnie et Herzégovine'),
('BB', 'Barbade (la)'),
('BD', 'Bangladesh'),
('BE', 'Belgique'),
('BF', 'Burkina-Faso'),
('BG', 'Bulgarie'),
('BH', 'Bahreïn'),
('BI', 'Burundi'),
('BJ', 'Bénin'),
('BL', 'Saint-Barthélémy'),
('BM', 'Bermudes'),
('BN', 'Brunei'),
('BO', 'Bolivie (l\'État plurinational de)'),
('BR', 'Brésil'),
('BS', 'Bahamas'),
('BT', 'Bhoutan'),
('BV', 'Îles Bouvet'),
('BW', 'Botswana'),
('BY', 'Biélorussie'),
('BZ', 'Belize'),
('CA', 'Canada'),
('CC', 'Îles Cocos-Keeling'),
('CD', 'Congo, République du'),
('CF', 'République Centrafricaine'),
('CG', 'Congo'),
('CH', 'Suisse'),
('CI', 'Côte D\'Ivoire'),
('CK', 'Îles Cook'),
('CL', 'Chili'),
('CM', 'Cameroun'),
('CN', 'Chine'),
('CO', 'Colombie'),
('CR', 'Costa Rica'),
('CU', 'Cuba'),
('CV', 'Cap-Vert'),
('CX', 'Île Christmas'),
('CY', 'Chypre'),
('CZ', 'République tchèque'),
('DE', 'Allemagne'),
('DJ', 'Djibouti'),
('DK', 'Danemark'),
('DM', 'Dominique (la)'),
('DO', 'République Dominicaine'),
('DZ', 'Algérie'),
('EC', 'Équateur (République de l\')'),
('EE', 'Estonie'),
('EG', 'Égypte'),
('EH', 'Sahara occidental'),
('ER', 'Érythrée'),
('ES', 'Espagne'),
('ET', 'Éthiopie'),
('FI', 'Finlande'),
('FJ', 'Fidji'),
('FK', 'Îles Malouines'),
('FM', 'Micronésie'),
('FO', 'Îles Féroé'),
('FR', 'France'),
('GA', 'Gabon'),
('GB', 'Royaume Uni'),
('GD', 'Grenade'),
('GE', 'Géorgie'),
('GF', 'Guyane française'),
('GG', 'Guernesey'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GL', 'Groenland'),
('GM', 'Gambie'),
('GN', 'Guinée'),
('GP', 'Guadeloupe (France DOM-TOM)'),
('GQ', 'Guinée Équatoriale'),
('GR', 'Grèce'),
('GS', 'Géorgie du Sud et Sandwich du Sud (ÎIes)'),
('GT', 'Guatemala'),
('GU', 'Guam'),
('GW', 'Guinée-Bissau'),
('GY', 'Guyane'),
('HK', 'Hong Kong'),
('HM', 'Îles Heard et Mc Donald'),
('HN', 'Honduras (le)'),
('HR', 'Croatie'),
('HT', 'Haïti'),
('HU', 'Hongrie'),
('ID', 'Indonésie'),
('IE', 'Irlande'),
('IL', 'Israël'),
('IM', 'Île de Man'),
('IN', 'Inde'),
('IO', 'Territoires Britanniques de l\'océan Indien'),
('IQ', 'Irak'),
('IR', 'Iran'),
('IS', 'Islande'),
('IT', 'Italie'),
('JE', 'Jersey'),
('JM', 'Jamaïque'),
('JO', 'Jordanie'),
('JP', 'Japon'),
('KE', 'Kenya'),
('KG', 'Kirghizistan'),
('KH', 'Cambodge'),
('KI', 'Kiribati'),
('KM', 'Comores'),
('KN', 'St Christopher et Nevis (Îles)'),
('KP', 'Corée du Nord'),
('KR', 'Corée'),
('KW', 'Koweït'),
('KY', 'Îles Caïmans'),
('KZ', 'Kazakhstan'),
('LA', 'République démocratique populaire du Laos'),
('LB', 'Liban'),
('LC', 'Saint-Lucie'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Liberia'),
('LS', 'Lesotho'),
('LT', 'Lituanie'),
('LU', 'Luxembourg'),
('LV', 'Lettonie'),
('LY', 'Jamahiriya arabe libyenne (Lybie)'),
('MA', 'Maroc'),
('MC', 'Monaco'),
('MD', 'Moldova (République de)'),
('ME', 'Monténégro'),
('MF', 'Saint-Martin'),
('MG', 'Madagascar'),
('MH', 'Îles Marshall'),
('MK', 'Macédoine, Ex-République yougoslave de'),
('ML', 'Mali'),
('MM', 'Myanmar (Union de)'),
('MN', 'Mongolie'),
('MO', 'Macao'),
('MP', 'Mariannes du Nord (Îles du Commonwealth)'),
('MQ', 'Martinique (France DOM-TOM)'),
('MR', 'Mauritanie'),
('MS', 'Montserrat'),
('MT', 'Malte'),
('MU', 'Île Maurice'),
('MV', 'Maldives'),
('MW', 'Malawi'),
('MX', 'Mexique'),
('MY', 'Malaisie'),
('MZ', 'Mozambique'),
('NA', 'Namibie'),
('NC', 'Nouvelle Calédonie'),
('NE', 'Niger'),
('NF', 'Île de Norfolk'),
('NG', 'Nigéria'),
('NI', 'Nicaragua'),
('NL', 'Pays-Bas'),
('NO', 'Norvège'),
('NP', 'Népal'),
('NR', 'Nauru (République de)'),
('NU', 'Niue'),
('NZ', 'Nouvelle Zélande'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Pérou'),
('PF', 'Polynésie française (DOM-TOM)'),
('PG', 'Papouasie Nouvelle-Guinée'),
('PH', 'Philippines'),
('PK', 'Pakistan'),
('PL', 'Pologne'),
('PM', 'Saint-Pierre-et-Miquelon (France DOM-TOM)'),
('PN', 'Pitcairn (Îles)'),
('PR', 'Porto Rico'),
('PS', 'Palestine (territoire occupé)'),
('PT', 'Portugal'),
('PW', 'Palau'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Réunion (Île de la)'),
('RO', 'Roumanie'),
('RS', 'Serbie'),
('RU', 'Fédération de Russie'),
('RW', 'Rwanda'),
('SA', 'Arabie Saoudite'),
('SB', 'Îles Salomon'),
('SC', 'Seychelles'),
('SD', 'Soudan'),
('SE', 'Suède'),
('SG', 'Singapour'),
('SH', 'Sainte Hélène'),
('SI', 'Slovénie'),
('SJ', 'Île Svalbard et Jan Mayen'),
('SK', 'Slovaquie'),
('SL', 'Sierra Leone'),
('SM', 'Saint-Marin'),
('SN', 'Sénégal'),
('SO', 'Somalie'),
('SR', 'Suriname'),
('ST', 'Sâo Tomé et Prince'),
('SV', 'Salvador'),
('SY', 'République arabe syrienne'),
('SZ', 'Swaziland'),
('TC', 'Îles Turks et Caïcos'),
('TD', 'Tchad'),
('TF', 'Terres Australes françaises (DOM-TOM)'),
('TG', 'Togo'),
('TH', 'Thaïlande'),
('TJ', 'Tajikistan'),
('TK', 'Îles Tokelau'),
('TL', 'Timor Oriental'),
('TM', 'Turkménistan'),
('TN', 'Tunisie'),
('TO', 'Tonga'),
('TR', 'Turquie'),
('TT', 'Trinité-et-Tobago'),
('TV', 'Tuvalu (Îles)'),
('TW', 'Taiwan'),
('TZ', 'Tanzanie'),
('UA', 'Ukraine'),
('UG', 'Ouganda'),
('UM', 'Dépendances américaines du Pacifique'),
('US', 'États-Unis'),
('UY', 'Uruguay'),
('UZ', 'Ouzbékistän'),
('VA', 'État de la cité du Vatican'),
('VC', 'Saint-Vincent et les Grenadines'),
('VE', 'Venezuela (République Bolivarienne du)'),
('VG', 'Îles Vierges britanniques'),
('VI', 'Îles Vierges américaines'),
('VN', 'Vietnam'),
('VU', 'Vanuatu (République de)'),
('WF', 'Wallis et Futuna'),
('WS', 'Samoa'),
('YE', 'Yémen'),
('YT', 'Mayotte'),
('ZA', 'Afrique du Sud'),
('ZM', 'Zambie'),
('ZW', 'Zimbabwe');
