
INSERT INTO `geo_fr_departement` (`id_departement`, `id_region`, `id_country`, `name`) VALUES
('01', 'B9', 'FR', 'Ain'),
('02', 'B6', 'FR', 'Aisne'),
('03', '98', 'FR', 'Allier'),
('04', 'B8', 'FR', 'Alpes de Haute Provence'),
('05', 'B8', 'FR', 'Hautes Alpes'),
('06', 'B8', 'FR', 'Alpes Maritimes'),
('07', 'B9', 'FR', 'Ardèche'),
('08', 'A4', 'FR', 'Ardennes'),
('09', 'B3', 'FR', 'Ariège'),
('10', 'A4', 'FR', 'Aube'),
('11', 'A9', 'FR', 'Aude'),
('12', 'B3', 'FR', 'Aveyron'),
('13', 'B8', 'FR', 'Bouches du Rhône'),
('14', '99', 'FR', 'Calvados'),
('15', '98', 'FR', 'Cantal'),
('16', 'B7', 'FR', 'Charente'),
('17', 'B7', 'FR', 'Charente Maritime'),
('18', 'A3', 'FR', 'Cher'),
('19', 'B1', 'FR', 'Corrèze'),
('20', 'A5', 'FR', 'Corse'),
('21', 'A1', 'FR', 'Côte d\'or'),
('22', 'A2', 'FR', 'Côtes d\'Armor'),
('23', 'B1', 'FR', 'Creuse'),
('24', '97', 'FR', 'Dordogne'),
('25', 'A6', 'FR', 'Doubs'),
('26', 'B9', 'FR', 'Drôme'),
('27', 'A7', 'FR', 'Eure'),
('28', 'A3', 'FR', 'Eure et Loir'),
('29', 'A2', 'FR', 'Finistère'),
('30', 'A9', 'FR', 'Gard'),
('31', 'B3', 'FR', 'Haute Garonne'),
('32', 'B3', 'FR', 'Gers'),
('33', '97', 'FR', 'Gironde'),
('34', 'A9', 'FR', 'Hérault'),
('35', 'A2', 'FR', 'Ille et Vilaine'),
('36', 'A3', 'FR', 'Indre'),
('37', 'A3', 'FR', 'Indre et Loire'),
('38', 'B9', 'FR', 'Isère'),
('39', 'A6', 'FR', 'Jura'),
('40', '97', 'FR', 'Landes'),
('41', 'A3', 'FR', 'Loir et Cher'),
('42', 'B9', 'FR', 'Loire'),
('43', '98', 'FR', 'Haute Loire'),
('44', 'B5', 'FR', 'Loire Atlantique'),
('45', 'A3', 'FR', 'Loiret'),
('46', 'B3', 'FR', 'Lot'),
('47', '97', 'FR', 'Lot et Garonne'),
('48', 'A9', 'FR', 'Lozère'),
('49', 'B5', 'FR', 'Maine et Loire'),
('50', '99', 'FR', 'Manche'),
('51', 'A4', 'FR', 'Marne'),
('52', 'A4', 'FR', 'Haute Marne'),
('53', 'B5', 'FR', 'Mayenne'),
('54', 'B2', 'FR', 'Meurthe et Moselle'),
('55', 'B2', 'FR', 'Meuse'),
('56', 'A2', 'FR', 'Morbihan'),
('57', 'B2', 'FR', 'Moselle'),
('58', 'A1', 'FR', 'Nièvre'),
('59', 'B4', 'FR', 'Nord'),
('60', 'B6', 'FR', 'Oise'),
('61', '99', 'FR', 'Orne'),
('62', 'B4', 'FR', 'Pas de Calais'),
('63', '98', 'FR', 'Puy de dôme'),
('64', '97', 'FR', 'Pyrénées-Atlantiques'),
('65', 'B3', 'FR', 'Hautes Pyrénées'),
('66', 'A9', 'FR', 'Pyrénées Orientales'),
('67', 'C1', 'FR', 'Bas Rhin'),
('68', 'C1', 'FR', 'Haut Rhin'),
('69', 'B9', 'FR', 'Rhône'),
('70', 'A6', 'FR', 'Haute Saône'),
('71', 'A1', 'FR', 'Saône et Loire'),
('72', 'B5', 'FR', 'Sarthe'),
('73', 'B9', 'FR', 'Savoie'),
('74', 'B9', 'FR', 'Haute Savoie'),
('75', 'A8', 'FR', 'Paris'),
('76', 'A7', 'FR', 'Seine Maritime'),
('77', 'A8', 'FR', 'Seine et Marne'),
('78', 'A8', 'FR', 'Yvelines'),
('79', 'B7', 'FR', 'Deux-Sèvres'),
('80', 'B6', 'FR', 'Somme'),
('81', 'B3', 'FR', 'Tarn'),
('82', 'B3', 'FR', 'Tarn et Garonne'),
('83', 'B8', 'FR', 'Var'),
('84', 'B8', 'FR', 'Vaucluse'),
('85', 'B5', 'FR', 'Vendée'),
('86', 'B7', 'FR', 'Vienne'),
('87', 'B1', 'FR', 'Haute-Vienne'),
('88', 'B2', 'FR', 'Vosges'),
('89', 'A1', 'FR', 'Yonne'),
('90', 'A6', 'FR', 'Territoire de Belfort'),
('91', 'A8', 'FR', 'Essonne'),
('92', 'A8', 'FR', 'Hauts de Seine'),
('93', 'A8', 'FR', 'Seine Saint Denis'),
('94', 'A8', 'FR', 'Val de Marne'),
('95', 'A8', 'FR', 'Val d\'Oise');
